name:
  icon

url:
  https://icon.sasaplus1.com

timezone:
  Asia/Tokyo

sass:
  style:
    nested

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
